
version: '3.7'

services:
  backend:
    build: 
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
    command: tail -f /dev/null
    container_name: backend
    ports:
      - 3000:3000
    networks:
      - hour-control

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - hour-control

networks:
  hour-control:
    driver: bridge